html = '''
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Html-Boil</title>
  <meta charset='UTF-8' />
  <link rel='stylesheet' type='text/css' href='static/style.css'/>
  <script type='text/javascript' src='static/index.js'></script>
</head>
<body>
  <h1>Hello, world!</h1>
</body>
</html>
'''

css = '''
html{
        background-color: black;
    }

    h1{
        color:white;
        text-align: center;
    }
'''

js = '''
console.log("Hello, World!");
'''